# Generated by Django 3.1.4 on 2022-11-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='blogs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
            preserve_default=False,
        ),
    ]
