# Generated by Django 3.1.4 on 2022-11-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221122_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
