# Generated by Django 3.1.4 on 2022-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('title', models.CharField(choices=[('MRS', 'mrs'), ('MR', 'mr'), ('MISS', 'miss')], default='MR', max_length=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
