# Generated by Django 3.1.4 on 2022-11-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20221115_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
