# Generated by Django 3.1.4 on 2022-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
