# Generated by Django 3.1.4 on 2022-11-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_auto_20221115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
